# use docker image with latex preinstalled
# since there is no official latex image, use https://github.com/blang/latex-docker
# possible alternative: https://github.com/natlownes/docker-latex
image: tetamusha/latex

build:
  script:
    - latexmk -pdf fei.dtx fei-template.tex fei-template-sublist.tex

  artifacts:
    paths:
      - "*.pdf"

pages:
  stage: deploy
  script:
  - mkdir .public
  - cp -r docs/* .public
  - mv .public public
  artifacts:
    paths:
    - public
  only:
  - master
