dist: trusty
sudo: required

language: minimal

before_install:
  - sudo apt-get update
  - sudo apt-get -yq install biber latexmk lmodern texlive-bibtex-extra texlive-fonts-recommended texlive-lang-portuguese texlive-latex-extra texlive-latex-recommended texlive-science xindy

script:
  - make fei.cls templates
